### PR TITLE
fix(index): ensure using the `raw` loader from the `css-resource-plugin`

### PR DESCRIPTION
**Pull request by stoffeastrom**

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@stoffeastrom I've been going back over things. It seems this is still a valid fix right? Can you confirm? If so, I can merge immediately. Let me know.

**Comment by stoffeastrom** [comment]
I've only tested 'local' require and haven't gotten an 'external' require to work yet.. I think it needs some more investigation so hold back on your merge finger ;-). I still think it's valid though

**Comment by EisenbergEffect** [comment]
Got it. I'll wait to hear from you. Thanks for investigating!

**Comment by stoffeastrom** [comment]
Unfortunately I thought it worked but after some more investigation it turned out that webpack added the css :pensive: I'm not sure this is possible and it's this part that I can't get to work

``` javascript
require.ensure([], function (require) {
  var result = require('aurelia-loader-context/' + path);
  if (typeof result === 'function') {
    result(function (res) {
      return resolve(res);
    });
  } else {
    resolve(result);
  }
});
```

**Comment by EisenbergEffect** [comment]
@stoffeastrom Should I close this out? Or do you have a solution or update to the PR?

**Comment by stoffeastrom** [comment]
No this should be closed

**Pull request closed without merging**
