### PR TITLE
Remove /*# sourceURL= */ from css-loader content

### LINKED ISSUE #61: Injected style elements: Multiple /* sourceURL */ lines causes browser devtools issues
**I'm submitting a bug report**

* **Library Version:**
2.2.4

**Please tell us about your environment:**
* **Operating System:**
Any OS (tested on Windows 11)

* **Node Version:**
LTS (16.17.0)

* **NPM Version:**
8.15.0

* **Webpack version**
webpack: 5.74.0
webpack-cli: 4.10.0
webpack-dev-server 4.10.1

* **Browser:**
all

* **Language:**
TypeScript 4.8.2

**Current behavior:**
For some time our Aurelia application had issues with altering CSS properties in chromium browsers (Chrome/Edge) **devtools**.
When trying to toggle certain CSS properties on/off through the "Styles" tab of the devtools "Elements" inspector, the CSS layout for major parts of the app immediately gets corrupted; certain selectors suddenly appear multiple times in the "Styles" tab, and the whole page looks messed up.

This really has complicated working with our app's design, so today I set out to find the root cause of the issue.
TLDR: I found that a fix is required in the `aurelia-loader-webpack` package, I have therfore prepared a PR.

We are using Sass (.scss) source code, and we use a standard `au-cli` generaated webpack configuration pipeline:
`sass-loader => postcss-loader => css-loader` for files `<require>`d from HTML templates, and with the additioinal `=> style-loader` for files imported from ES modules. (Source maps are enabled for the loaders when webpack `mode=development`).

**Steps taken to identify the problem:**
* First I noticed that the problem only occurs when toggling CSS properties "source-mapped" from **.scss** files.
* Then I noticed that it only happened for **.scss** files that include sass `@use` (or `@import`) rules.
* I then used the Chrome devtools DOM inspector to look at the injected `<style>` elements that originated from **.scss** files with `@use` rules, and noticed that these had **multiple** `/* sourceURL=[path] */` lines at the end; just before the `/* sourceMappingURL=[dataURI] */`. (One for the source file, and then one for each `@use` rule).
* Then I saw that manually _removing these `sourceURL` lines from the DOM fixes the problem_.
* I then noticed that `sourceURL` lines are never included when using `style-loader` (f.ex. when importing from ES modules), only when using `aurelia-loader-webpack` (when loaded from HTML templates).

It looks like multiple `sourceURL` lines affect the way sourceMapping works in chromium devtools; it seems like the devtools only considers the last of the `sourceURL` lines.

I therefore have tried to find a way to make `aurelia-loader-webpack` style element injection work like `style-loader`; to not include the `sourceURL` lines, only include the `sourceMappingURL` line (when sourceMaps).

The `.toString()` method from the loaded `css-loader` module that is called in [`aurelia-loader-webpack.ts:241`](https://github.com/aurelia/loader-webpack/blob/master/src/aurelia-loader-webpack.ts#L241) returns the full CSS content, with both `sourceURL` and `sourceMappingURL` lines.

I therefore found two possible solutions to fix the problem:
1. Still use the `toString()` method, and use a RegExp to remove the `sourceURL` lines (only executed when the loaded `css-loader` module has sourceMaps).
2. Manually construct the CSS content with potential sourceMappingURL from the loaded `css-loader` module properties. This can be accomplished by reusing some of the code from the `css-loader` repository, and skip the `sourceURL` generation.

**Pros/cons:**
Solution 1: Low vulnerability to breaking changes in `css-loader` package but has a minor performance impact.
Solution 2: More vulnerable to **major** changes in the `css-loader` package, but with zero performance impact.

I have forked this repository and implemented solutions 1. and 2. on two different branches:
* [Solution 1](https://github.com/aurelia/loader-webpack/compare/master...josundt:loader-webpack:josundt/css-sourceurl-fix)
* [Solution 2](https://github.com/aurelia/loader-webpack/compare/master...josundt:loader-webpack:josundt/css-sourceurl-fix-2)

I have tested both solutions in our app, and they both fix the problem.
PS! Solution 2 reuses the exact code from the `toString()` in the `style-loader` loader, but the writing of the `sourceURL` lines have been excluded.

I hope you acknowledge this as a problem, and realize that a fix is needed here.
I have not created a PR yet, because I wanted some feedback on which of the solutions you prefer.
Please get back to me, hopefully with your preferred solution, so that I can make a PR.

**Expected/desired behavior:**
Altering CSS through devtools should work.

### PR DESCRIPTION
**Pull request by josundt**
Fixes #61.

Waiting for a package release.
I guess a release of **aurelia-webpack-plugin** might also be desirable to update the version constraint for **aurelia-loader-webpack**.

### CODE REVIEW

**Comment by josundt** [comment]
It looks like the circleci build failed.
Since the build pipeline uses `npm install` instead of `npm ci`, I guess a newer version of the **"@rollup/plugin-typescript": "^8.2.3"** package was used compared to the previous build, and this new version seems to expect **tslib** as a peer dependency.

**Comment by bigopon** [comment]
probably it shouldn't be npm i. We can lock the version and do npm ci in the pipeline. Can you also push that change into this PR? For the release, it'll probably take another few hours. I've got a few things on my plate at the moment.

**Comment by josundt** [comment]
@bigopon 
I can do that.
I also found that package-lock.json references **aurelia-path@1.1.5**.
This package reports a npm audit vulnerability which has been mitigated in **1.1.7** (latest).

Running `npm audit fix` mitigates this, and updates package-lock.json (only changes reference for aurelia-path).
Is it OK to also include this?

**Comment by bigopon** [comment]
Hmm, that sounds like a bit too much to ask a contributor. Maybe let me take care of it, I'll be also updating a few other stuff in this repo. Thanks for pointing that out 👍

**Comment by josundt** [comment]
That's OK 🙂. 
I've updated the circleci yaml file👍

**Comment by josundt** [comment]
Seems it still did not fix the build issue though.
Not sure why...
`npm run build` works fine on my machine after running `npm ci`...

**Comment by josundt** [comment]
@bigopon 
circleci build uses Node 12.x.

I got the same error on my machine when running `npm ci` + `npm run build` on Node 12 (12.22.12).
But with Node LTS (16.17.0), everything works fine.

Can I change the circleci yaml file to `image: circleci/node:16` instead of `image: circleci/node:12`?

**Comment by bigopon** [comment]
@josundt just got back to this, and I took over to get it out faster, hope you dont mind. I've changed node to 16 for your last question. Thanks for the analysis and the work.

**Comment by josundt** [comment]
@bigopon Just tested the new release in our app, and it fixes the SCSS => CSS source map problem as expected 👍
Thanks for your quick support once again! 🙂

**Pull request merged**
