### PR TITLE
Merged aurelia-loader-webpack

### PR DESCRIPTION
**Pull request by martijnboland**
This is the merge of https://github.com/martijnboland/aurelia-loader-webpack with this repository. The gulp tasks are working and a local version of the npm package is tested locally with the skeleton-webpack app.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
Happy to get this in pending CLA sign :smile: https://docs.google.com/a/durandal.io/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1

**Comment by EisenbergEffect** [comment]
Thanks! Maybe we can convince you to build us a skeleton project and submit to the skeleton repo :)

**Comment by EisenbergEffect** [comment]
Out of curiosity...is this going to have to change for Webpack 2.x?

**Comment by martijnboland** [comment]
Skeleton in progress: https://github.com/martijnboland/skeleton-navigation/tree/webpack/skeleton-es2016-webpack. Currently referencing aurelia-loader-webpack from my own repo because this one doesn't contain the /dist files and there is no NPM package yet.

**Comment by EisenbergEffect** [comment]
I can do an initial release to npm today. I'll update here when it's out.

**Comment by EisenbergEffect** [comment]
@martijnboland Releases up.

**Comment by martijnboland** [comment]
Great!

**Pull request merged**
